"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useRecommendations } from "@/hooks/use-recommendations";
import { Sparkles, ArrowRight, Info, CheckCircle2 } from "lucide-react";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

export function AIRecommendations() {
  const { data, isPending, isError } = useRecommendations({ pageSize: 10 });

  // backend priority is CRITICAL/HIGH/MEDIUM/LOW, these components switch on lower case.
  // currentInventory and forecastDemand have no backend source, so they are omitted
  // rather than filled with a number nothing produced.
  const recommendations = (data?.data ?? []).map((rec) => ({
    id: rec.id,
    itemId: rec.sku,
    action: rec.actionType ?? rec.type,
    priority: rec.priority.toLowerCase(),
    reason: rec.message,
    expectedImpact: rec.expectedImpact ?? "",
    confidenceScore: rec.confidence ?? 0,
    suggestedQuantity: rec.quantity ?? 0,
    sourceDc: null as string | null,
    destinationDc: rec.warehouseCode,
    // a recommendation does not carry the position it was derived from. showing a
    // dash beats inventing a stock level.
    currentInventory: null as number | null,
    forecastDemand: null as number | null,
    impactValue: rec.impactValue,
  }));

  if (isPending || isError) {
    return (
      <Card>
        <CardContent className="py-6 text-sm text-muted-foreground">
          {isPending ? "Loading recommendations…" : "Could not load recommendations."}
        </CardContent>
      </Card>
    );
  }

  if (recommendations.length === 0) {
    return (
      <Card>
        <CardContent className="py-6 text-sm text-muted-foreground">
          No recommendations yet. Run the planner to generate them.
        </CardContent>
      </Card>
    );
  }

  const getPriorityColor = (priority: string) => {
    switch(priority) {
      case "critical": return "bg-destructive text-[#FFFFFF] hover:bg-destructive/90 border-transparent";
      case "high": return "bg-warning text-[#FFFFFF] hover:bg-warning/90 border-transparent";
      case "medium": return "bg-primary/20 text-primary hover:bg-primary/30";
      case "low": return "bg-muted text-muted-foreground hover:bg-muted/80";
      default: return "";
    }
  };

  return (
    <Card className="flex flex-col shadow-sm h-full">
      <CardHeader className="pb-4 border-b border-border/50">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2 text-base">
              <Sparkles className="h-4 w-4 text-ai" />
              AI Recommended Actions
              <Tooltip>
                <TooltipTrigger render={<Info className="h-4 w-4 text-muted-foreground cursor-help" />} />
                <TooltipContent>
                  <p className="max-w-xs">WHAT ACTION should be taken. Contextualized recommendations generated by the optimization engine to resolve identified risks.</p>
                </TooltipContent>
              </Tooltip>
            </CardTitle>
            <CardDescription>Prescriptive actions to mitigate risk and optimize network</CardDescription>
          </div>
          <Badge variant="outline" className="bg-ai/10 text-ai border-ai/20">
            {recommendations.length} Pending
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="p-0 flex-1 overflow-y-auto min-h-0">
        <div className="flex flex-col divide-y divide-border/50">
          {recommendations.map((rec) => (
            <div key={rec.id} className="px-4 py-4 flex flex-col gap-4 transition-colors hover:bg-muted/20">
              <div className="flex items-start justify-between gap-4">
                <div className="flex flex-col gap-1">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-base text-foreground uppercase tracking-tight">{rec.action === "order" ? "Replenish" : rec.action === "transfer" ? "Transfer" : "Prioritize"} {rec.suggestedQuantity.toLocaleString()} units</span>
                    <Badge variant="outline" className={`capitalize border-transparent ${getPriorityColor(rec.priority)}`}>
                      {rec.priority} Priority
                    </Badge>
                  </div>
                  <div className="text-sm font-medium text-foreground/90 mt-1">{rec.reason}</div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground mt-2 font-mono">
                    <span className="bg-muted px-2 py-0.5 rounded text-foreground">{rec.itemId}</span>
                    {rec.sourceDc && <span>From: <span className="text-foreground">{rec.sourceDc}</span></span>}
                    {rec.destinationDc && <span>To: <span className="text-foreground">{rec.destinationDc}</span></span>}
                  </div>
                </div>
                <div className="flex flex-col items-end gap-2 shrink-0">
                  <div className="flex items-center gap-1.5 bg-success/10 text-success px-2.5 py-1 rounded-md">
                    <CheckCircle2 className="h-3.5 w-3.5" />
                    <span className="text-xs font-bold">{rec.confidenceScore}% Confidence</span>
                  </div>
                </div>
              </div>
              
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 bg-muted/40 p-3 rounded-lg border border-border/50">
                <div className="flex flex-col gap-1">
                  <span className="text-[10px] uppercase tracking-wider text-muted-foreground">Current Stock</span>
                  <span className="text-sm font-semibold tabular-nums">{rec.currentInventory?.toLocaleString() ?? "—"}</span>
                </div>
                <div className="flex flex-col gap-1">
                  <span className="text-[10px] uppercase tracking-wider text-muted-foreground">Forecast Demand</span>
                  <span className="text-sm font-semibold tabular-nums">{rec.forecastDemand?.toLocaleString() ?? "—"}</span>
                </div>
                <div className="flex flex-col gap-1 md:col-span-2">
                  <span className="text-[10px] uppercase tracking-wider text-muted-foreground">Expected Impact</span>
                  <span className="text-sm font-semibold text-success">{rec.expectedImpact}</span>
                </div>
              </div>
              
              <div className="flex justify-end gap-2 mt-1">
                <Button variant="outline" size="sm" className="h-8">Dismiss</Button>
                <Button size="sm" className="h-8 gap-1.5 cursor-pointer bg-primary text-primary-foreground hover:bg-primary/90 group">
                  Execute Action <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" />
                </Button>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
